# Generated by Django 3.2.9 on 2022-01-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('text_article', models.CharField(max_length=1000, verbose_name='text_article')),
                ('topic', models.CharField(max_length=50, verbose_name='topic')),
                ('fecha_inscripcion', models.DateField(verbose_name='date_creation')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='user')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('fecha_inscripcion', models.DateField(verbose_name='date_subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='user')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
        ),
    ]
