# Generated by Django 3.2.9 on 2022-01-16 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20220116_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_creation',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date_creation'),
        ),
    ]
